# Generated by Django 6.0.5 on 2026-06-30 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_perfil_portada_alter_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id_capitulo', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('palabras', models.PositiveIntegerField(blank=True, default=0)),
                ('fecha_creacion', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='blog.libro')),
            ],
            options={
                'db_table': 'capitulo',
                'ordering': ['numero'],
                'unique_together': {('libro', 'numero')},
            },
        ),
    ]
