# Generated by Django 6.0.5 on 2026-06-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_delete_post_usuario_telefono_alter_amistad_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/', verbose_name='Imagen de portada'),
        ),
    ]
